use continuum_core::{HTML_MIME, PLAIN_TEXT_MIME, PNG_MIME, RTF_MIME, TIFF_MIME};

pub const SUPPORTED: &[&str] = &[PLAIN_TEXT_MIME, HTML_MIME, RTF_MIME, PNG_MIME, TIFF_MIME];

#[cfg(target_os = "macos")]
pub mod native {
    use continuum_core::{HTML_MIME, PLAIN_TEXT_MIME, PNG_MIME, RTF_MIME, TIFF_MIME};

    pub const PLAIN_TEXT: &str = "public.utf8-plain-text";
    pub const HTML: &str = "public.html";
    pub const RTF: &str = "public.rtf";
    pub const PNG: &str = "public.png";
    pub const TIFF: &str = "public.tiff";

    #[must_use]
    pub fn to_native(mime: &str) -> Option<&'static str> {
        match mime {
            PLAIN_TEXT_MIME => Some(PLAIN_TEXT),
            HTML_MIME => Some(HTML),
            RTF_MIME => Some(RTF),
            PNG_MIME => Some(PNG),
            TIFF_MIME => Some(TIFF),
            _ => None,
        }
    }

    #[must_use]
    pub fn from_native(native: &str) -> Option<&'static str> {
        match native {
            PLAIN_TEXT => Some(PLAIN_TEXT_MIME),
            HTML => Some(HTML_MIME),
            RTF => Some(RTF_MIME),
            PNG => Some(PNG_MIME),
            TIFF => Some(TIFF_MIME),
            _ => None,
        }
    }
}

#[cfg(target_os = "linux")]
pub const SENSITIVE_MARKERS: &[&str] = &["x-kde-passwordManagerHint"];

#[cfg(target_os = "macos")]
pub const SENSITIVE_MARKERS: &[&str] = &[
    "org.nspasteboard.TransientType",
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.AutoGeneratedType",
    "com.apple.is-remote-clipboard",
];

#[must_use]
pub fn is_sensitive(native_types: &[String]) -> bool {
    native_types
        .iter()
        .any(|ty| SENSITIVE_MARKERS.contains(&ty.as_str()))
}
