[package]
name = "continuum-net"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Discovery, transport and crypto for Continuum peers"

[dependencies]
bincode = "1"
blake3 = "1.8.7"
continuum-core.workspace = true
dirs = "7.0.0"
serde = { version = "1.0.229", features = ["derive"] }
snow = "0.9.6"
thiserror = "2.0.21"

[lints]
workspace = true
